FROM mcr.microsoft.com/vscode/devcontainers/base:debian-10

# Reference - https://github.com/microsoft/vscode-dev-containers/blob/master/containers/markdown/.devcontainer/Dockerfile
# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>